image: node:lts
test:
  stage: test
  image: ghcr.io/catthehacker/ubuntu:act-latest
  script:
    - |
      echo "Host arch: $(uname -m)"
      export DEBIAN_FRONTEND=noninteractive
      sudo apt update
      wget -qO- https://deb.nodesource.com/setup_current.x | sudo bash -
      packages=( "binutils-multiarch" "wget" "curl" "nodejs" );
      if [[ $(uname -m) == "x86_64" ]];then
        packages+=( "gcc-*aarch64-linux-gnu" "gcc-*aarch64-linux-gnu-base" "g++-*aarch64-linux-gnu" "libc6-arm64-cross" )
      else
        packages+=( "libc6-amd64-cross" "g++-*x86-64-linux-gnu" "g++-*x86-64-linux-gnux32" "gcc-*x86-64-linux-gnu" "gcc-*x86-64-linux-gnux32" )
        if [[ $(uname -m) != "aarch64" ]];then
          packages+=( "gcc-*aarch64-linux-gnu" "gcc-*aarch64-linux-gnu-base" "g++-*aarch64-linux-gnu" "libc6-arm64-cross" )
        fi
      fi
      sudo apt install -y ${packages[@]}
    - npm install --no-save --ignore-scripts
    - npm run prebuildify -- -v
    - sudo node --require ts-node/register --loader ts-node/esm ./src/index_test.ts
