image: node:lts
test:
  stage: test
  image: ghcr.io/catthehacker/ubuntu:act-latest
  script:
    - |
      echo "Host arch: $(uname -m)"
      export DEBIAN_FRONTEND=noninteractive
      sudo apt update
      wget -qO- https://deb.nodesource.com/setup_current.x | sudo bash -
      packages=( "binutils-multiarch" "wget" "curl" "nodejs" "build-essential" );
      sudo apt install -y ${packages[@]}

      ZIGURL="https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz"
      wget -qO- "${ZIGURL}" | sudo tar -xvJ -C /usr/local
      sudo mv -v /usr/local/zig-* /usr/local/zig
      sudo ln -vs /usr/local/zig/bin/zig /usr/bin/zig

    - npm install --no-save --ignore-scripts
    - npm run dev
    - sudo node --no-warnings --loader ts-node/esm ./src/index_test.ts
