name: Devcontainer Test
on:
  push:
    branches: [ "main" ]
    paths:
      - ".devcontainer/**/*"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".devcontainer/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .devcontainer/
          push: false
          tags: devcontainer:latest
          load: true
      - run: docker run --rm -i devcontainer:latest exit 0