name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        node_version:
          - 14.x
          - 16.x
          - 18.x
          - latest
        os:
          - ubuntu
          - windows
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm install --no-save && ${{ matrix.os == 'ubuntu' && 'sudo ' || '' }}npm install -g ts-node typescript mocha && npm run build

      - name: Test
        run: npm run test${{ matrix.os == 'windows' && ':win' || '' }}

      - name: Print route and address
        if: matrix.os == 'ubuntu'
        continue-on-error: true
        run: |
          sudo ip route show all | grep sh23Test1235555
          sudo ip addr show sh23Test1235555